version: '2'
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    expose:
      - 5432
    networks:
      - all
    environment:
      POSTGRES_USER: chatty_tammy
      POSTGRES_PASSWORD: gossipy
      POSTGRES_DB: chitchat
networks:
  all:
    driver: bridge
